### ISSUE TITLE
ThemeKit crashes on launch

### ISSUE THREAD

**Issue by marshmello-colin** [ThemeKitApp/ThemeKit#2]
Process:               ThemeKit [1081]
Path:                  /private/var/folders/*/ThemeKit.app/Contents/MacOS/ThemeKit
Identifier:            com.mtac.ThemeKit
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           ThemeKit [1081]
User ID:               501

Date/Time:             2020-05-01 09:14:40.768 -0700
OS Version:            Mac OS X 10.15.3 (19D76)
Report Version:        12
Bridge OS Version:     4.2 (17P3050)
Anonymous UUID:        EF2218D0-FFA5-F6F9-D8C6-4B53EC7B865D

Sleep/Wake UUID:       D0C88DBD-43C2-4E73-8BA3-6B7E4661FEFB

Time Awake Since Boot: 1300 seconds
Time Since Wake:       870 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 0000000107005000-0000000107014000 [   60K] r-x/r-x SM=COW  

Thread 0 Crashed:
0                                 	0x00000001084b8000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee8bfab58
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00000001084b8000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0

Binary Images:
       0x107005000 -        0x107013ff3 + (0) <4D190F16-3D9B-310B-AD11-674B030F2290> 
       0x1084b7000 -        0x108547cb7 + (733.8) <EBC07CB6-870A-3A8E-B48A-67F62EA161F3> 

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 1211
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=920K resident=0K(0%) swapped_out_or_unallocated=920K(100%)
Writable regions: Total=8404K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8404K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                             228K        3 
__DATA_CONST                        24K        2 
__LINKEDIT                         280K        2 
__TEXT                             640K        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                             65.2M       13 

Model: MacBookPro15,2, BootROM 1037.80.53.0.0 (iBridge: 17.16.13050.0.0,0), 4 processors, Quad-Core Intel Core i5, 2.3 GHz, 16 GB, SMC 
Graphics: kHW_IntelIrisGraphics655Item, Intel Iris Plus Graphics 655, spdisplays_builtin
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, LPDDR3, 2133 MHz, Samsung, K4EBE304EC-EGCG
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, LPDDR3, 2133 MHz, Samsung, K4EBE304EC-EGCG
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x7BF), wl0: Dec  6 2019 11:17:27 version 9.112.4.0.32.5.41 FWID 01-ac611e8a
Bluetooth: Version 7.0.3f5, 3 services, 18 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: Apple T2 Bus
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 41.2
Thunderbolt Bus: MacBook Pro, Apple Inc., 41.2

**Comment by M4cs** [comment]
You have SIP enabled. Please refer to the Wiki and follow all of the instruction on how to install ThemeKit [Here](https://github.com/ThemeKitApp/ThemeKit/wiki/Setup-and-Usage#getting-started)

**Comment by marshmello-colin** [comment]
Still won't launch after disabling SIP and following the Getting Started page.

Process:               ThemeKit [750]
Path:                  /Applications/ThemeKit.app/Contents/MacOS/ThemeKit
Identifier:            com.mtac.ThemeKit
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           ThemeKit [750]
User ID:               501

Date/Time:             2020-05-01 11:34:31.963 -0700
OS Version:            Mac OS X 10.15.3 (19D76)
Report Version:        12
Bridge OS Version:     4.2 (17P3050)
Anonymous UUID:        EF2218D0-FFA5-F6F9-D8C6-4B53EC7B865D


Time Awake Since Boot: 220 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 0000000106bfd000-0000000106c11000 [   80K] r-x/r-x SM=COW  

Thread 0 Crashed:
0                                 	0x0000000106fa7000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee9002bd0
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x0000000106fa7000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0


Binary Images:
       0x106bfd000 -        0x106c10ffb + (0) <A6E8620E-69C7-3380-91C7-2AF7D04804FD> 
       0x106fa6000 -        0x107036cb7 + (733.8) <EBC07CB6-870A-3A8E-B48A-67F62EA161F3> 

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 132
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=952K resident=0K(0%) swapped_out_or_unallocated=952K(100%)
Writable regions: Total=8404K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8404K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                             236K        3 
__DATA_CONST                        20K        1 
__LINKEDIT                         292K        2 
__TEXT                             660K        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                             65.2M       12
